spring.application.name=bank

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:devsubank}
spring.datasource.username=${DB_USER:devsu}
spring.datasource.password=${DB_PASSWORD:devsu123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
